Feature/chat
TripleSync/TS pull request #2
Opened 2024-10-18 08:31 UTC by sdj799

## #️⃣ 연관된 이슈

> #1 

## 📝 작업 내용

> 웹소켓을 이용한 채팅 기능 구현

### 스크린샷 (선택)
![image](https://github.com/user-attachments/assets/2dddf63a-8cb7-41ee-b030-d2b3d5ab5e79)

## 💬 리뷰 요구사항(선택)

> 디자인은 기능 구현 다 한 후에 다시 손 보겠습니다.
> 웹 소켓 서버는 server폴더를 루트로 잡으신 후 node server.js 명령어 입력하시면 5000번으로 돌아갑니다.
> 자신의 채팅을 오른쪽에 위치하는 기능은 추후 개발 예정입니다.

2024-10-19 11:11 UTC, handje requested changes

2024-10-19 11:11 UTC, handje commented on src/components/Chat.tsx
> +  const user: User = { userName: "user1", profileUrl: profil };
이부분의 userName이 변동되는건 추후에 추가하실 예정이신가요?

2024-10-19 11:11 UTC, handje commented on server/server.js
> +  cors: { origin: "http://localhost:5173", methods: ["GET", "POST"] },
하나의 포트만 허용하면 다른 포트를 키고 테스트가 안되는것 같습니다! 전체허용(*)으로 하면 동작하긴하는데 이렇게 하신 이유가 있다면 코멘트 남겨주세요 :)

2024-10-20 04:08 UTC, mya413 requested changes

2024-10-20 04:08 UTC, mya413 commented on src/store/actions/useChatStore.ts
> +}));
chat 기능의 상태를 useState, props가 아닌 전역 상태로 관리하는 이유가 궁금합니다!

2024-10-21 04:09 UTC, sdj799 commented on src/components/Chat.tsx
> +  const user: User = { userName: "user1", profileUrl: profil };
기존 로그인을 했을 때를 생각해서 로그인 되어있는 유저 정보를 가져오는 것으로 진행하려 했는데 테스트를 하려면 userName을 변경하는 작업도 필요한 것 같습니다. 추가해 보도록 하겠습니다.

2024-10-21 04:13 UTC, sdj799 commented on server/server.js
> +  cors: { origin: "http://localhost:5173", methods: ["GET", "POST"] },
cors를 미리 설정해 두려고 했는데 테스트할 때 정상적으로 작동이 안될까요?
전체허용으로 바꾼 후 기능 개발이 다 완료 되면 설정 변경하겠습니다.

2024-10-21 04:15 UTC, sdj799 commented on src/store/actions/useChatStore.ts
> +}));
일단 아직 모듈화를 진행하지 않았는데 모듈화가 진행되면 zustand로 상태 관리를 하는 것이 더 효율적으로 생각하여 미리 세팅해 두었습니다.

2024-10-21 11:00 UTC, handje commented
- 기본 폴더 구조 (components > ClassRoom 폴더 생성)
- 색 설정 변경
- 서버 코드 수정
- 절대경로 설정
기존 코드에 위에 4가지 확인 후 merge 진행예정

2024-10-22 05:47 UTC, handje approved these changes

2024-10-22 05:47 UTC, mya413 approved these changes

2024-10-22 05:48 UTC, merged