feat: 프로필 사진 url로 구현
TripleSync/TS pull request #25
Opened 2024-11-12 14:40 UTC by sdj799

## #️⃣ 연관된 이슈

> #16 

## 📝 작업 내용

> 파일 첨부 이슈로 인한 프로필 사진 변경을 url로 변경

### 스크린샷 (선택)
![image](https://github.com/user-attachments/assets/806eff8a-1a19-4ba6-9b8d-8acf789338ae)

## 💬 리뷰 요구사항(선택)

2024-11-13 04:55 UTC, handje requested changes
기능적인 문제는 없는데 제 노트북 기준 100%배율에서 회원가입창이 위아래가 잘려서 보입니다!
![image](https://github.com/user-attachments/assets/b7468b6d-ec64-480f-976c-82f8cf761712)

2024-11-14 12:05 UTC, sdj799 commented
> 기능적인 문제는 없는데 제 노트북 기준 100%배율에서 회원가입창이 위아래가 잘려서 보입니다! ![image](https://private-user-images.githubusercontent.com/57988006/385593068-b7468b6d-ec64-480f-976c-82f8cf761712.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1ODUxNzcsIm5iZiI6MTczMTU4NDg3NywicGF0aCI6Ii81Nzk4ODAwNi8zODU1OTMwNjgtYjc0NjhiNmQtZWM2NC00ODBmLTk3NmMtODJmOGNmNzYxNzEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDExNDc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjMDdmMDU2Njk4NDQyZjUwYzg0OTRjZTdiOGJiNmU2ZWY1NTcyZjBhNDRjNThkM2YyYmY4M2IyNThhNTcwYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SzMXdN0RZ3UIKTOBZqISZiJ4eMDtvgHqZducRmlOoCI)

반응형 추가해서 커밋했습니다!

2024-11-15 04:59 UTC, handje approved these changes
👍 👍

2024-11-16 06:33 UTC, handje requested changes
모달창이 아래까지 내려오지 않도록 해주세요! 전체 높이를 차지하는건 다른 동작에 방해가 될 것 같습니다

2024-11-27 09:05 UTC, handje approved these changes
좋네요 ! 👍 👍

2024-11-27 12:25 UTC, merged