refactor: 채팅 컴포넌트 모듈화 및 최적화
TripleSync/TS pull request #4
Opened 2024-10-23 08:50 UTC by sdj799

## #️⃣ 연관된 이슈

> #1 

## 📝 작업 내용

> 채팅 컴포넌트 모듈화, 최적화 진행했습니다.

### 스크린샷 (선택)

## 💬 리뷰 요구사항(선택)

>

2024-10-23 09:09 UTC, handje requested changes
https://github.com/TripleSync/TS/pull/5
해당 pr 머지 후, 기본 컴포넌트 구조 수정하시고 merge부탁드릴게요!
page>ClassRoom 부분 수정이 발생했습니다.

2024-10-23 09:09 UTC, handje commented on src/components/ClassRoom/Chat.tsx
> +      socket.emit("message", { user: user, text: text, time: new Date() });
time이 표현되는 부분이 수정이 필요해보입니다! 지금은 시간이 제대로 표현되지 않는것으로 보입니다 😢

2024-10-23 10:49 UTC, sdj799 commented on src/components/ClassRoom/Chat.tsx
> +      socket.emit("message", { user: user, text: text, time: new Date() });
memo를 잘못 적용해서 오류가 난 것 같습니다. 수정 후 푸쉬하였습니다.

2024-10-23 10:58 UTC, mya413 approved these changes
👏🏻👏🏻

2024-10-24 15:50 UTC, handje approved these changes
충돌 해결하시구 머지 진행해주세요 ! 👍 👍

2024-10-26 02:08 UTC, merged